x=Msgbox ("Thanks for using OPTIMIZER FOR WINDOWS, this will close many applications, please close any apps for avoid lose data now.", 0+64, "Info")
x=Msgbox ("Cmd will be runned as an administrator while the process is doing his job, please do not TOUCH the PC until a message appears that says ''Done!'' ", 0+48, "Information")
x=Msgbox ("Apps that will be closed soon : Outlook, Word, Powerpoint, Notepad, Task Manager, ALL HP services, Intel Services, Widgets, Media player, Canva, Microsoft edge, Your Phone, My HP, Opera, ETD SERVICE, Elan service, System settings, Epic Games launcher, XBOX game bar, Gaming services, Photos, OneDrive, DLL Host, Runtime Broker and other apps and windows services and settings...", 0+48, "Apps that will be closed")
x=Msgbox ("Some apps that you see might not be downloaded to your pc, don't worry these apps that you see is not harmful", 0+48, "Information")
x=Msgbox ("Confirm ?", 0+32, "Warn 1/3")
x=Msgbox ("Are you sure you still want to close all apps ?", 0+32, "Warn 2/3")
x=Msgbox ("Last warning, please make sure to save data before it gets lost, SYSTEM APPS WILL BE CLOSED TOO, IT CAN MAYBE CAUSE CRASH TO YOUR PC, THIS SCRIPT HAS BEEN TESTED ON ONLY ONE PC AND RESULTS CANNOT CONFIRM THAT THIS SCRIPT CAN BE STABLE FOR OTHER PC." &vbLf& "" &vbLf& "USE IT AT YOUR OWN RISK!" &vbLf& "IM NOT RESPONSIBLE FOR ANY DAMAGES TO THE PC" &vbLf& "" &vbLf& "PRESS HELP BUTTON TO CANCEL IF YOU DON'T WANT TO EXECUTE! YOU NEED AT LEAST 1.20 GHz CPU SPEED TO ENSURE SCRIPT WORKS WELL!", 0+16, "Warn 3/3",xPos,yPos)
Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.Run "cmd"
WScript.sleep 3000
Wshshell.sendkeys "Cmd administrator"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /PID 7516"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /Im DSATray.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /Im Notepad.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "taskkill /f /im taskmgr.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "taskkill /F /IM HxOutlook.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /im TouchpointAnalyticsClientService.exe /T"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /IM winword.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /IM Mspaint.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /Im Clipchamp.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /IM Vlc.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "taskkill /F /Im Powerpnt.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "taskkill /F /IM Widgets.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "taskkill /F /IM microsoft.media.player.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "taskkill /f /Im Canva.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im msedge.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /IM YourPhone.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /IM MsMpEng.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /Im HP.MyHP.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /Im opera.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im ETDCrtl.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /IM ETDService.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im SystemSettings.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /IM DSAService.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /IM SDUpdSvc.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im WebViewHost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /Im HPSystemEventUtilityHost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /Im EpicGamesLauncher.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /Im HelpPane.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /F /Im GameBar.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im msedgewebview2.exe /T"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im msedgewebview2.exe /T"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im msedgewebview2.exe /T"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im msedgewebview2.exe /T"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im gamingservicesnet.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im gamingservices.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im HxTsr.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im RuntimeBroker.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im SysinfoCap.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im Microsoft.Photos.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im DiagsCap.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im dasHost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im StartMenuExperienceHost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im spoolsv.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im dllhost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im DisplaySwitch.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im diskmgmt.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im AppHelperCap.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im ctfmon.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im msiexec.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im OneDriveStandaloneUpdater.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im fontdrvhost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im smartscreen.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im ntoskrnl.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im SearchHost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im TextInputHost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im WebExperienceHostApp.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im WmiPrvSE.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im IGCC.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im backgroundTaskHost.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im Winver.exe"
Wshshell.sendkeys "{ENTER}"
Wshshell.sendkeys "Taskkill /f /im regedit.exe"
Wshshell.sendkeys "{ENTER}"
WScript.sleep 7000
x=Msgbox ("Done! You can now close CMD and this message! if theres still performance issues, please try to restart your computer then try to execute this app again")












